JsOsaDAS1.001.00bplist00ÑVscript_& 
var csvPath = "~/dev/mobfriendly/loadtimes.csv";
var screensPath = "~/dev/mobfriendly/screens/";
var screencapFreq = 250;
var loadTimeout = 20000;

function getBoundsString(window, maxWidth, maxHeight) {
	var bounds = window.bounds();
	var width = Math.min(bounds.width, maxWidth);
	var height = Math.min(bounds.height, maxHeight);
	return "" + bounds.x +","+ bounds.y +","+ width +","+ height;
}

function doScript(terminal, script) {
	var termw = terminal.windows()[0];
	terminal.doScript(script, {in: termw});
}

function screencap(window, terminal, filename) {
	var boundString = getBoundsString(window, 500, 900);
	termw = terminal.windows()[0];
	doScript(terminal, 
		"screencapture -R" + boundString + " " + screensPath +
		filename + ".png");
}

function getUrl(chromeWindow, terminal, url) {
	// Create subdir.
	doScript(terminal, "mkdir " + screensPath + "/" + url);
	
	// Clean.
	chromeWindow.activeTab.url = "about:blank";
	while (w.activeTab.loading()) {
		// Pass.
	}
	
	// Load site.
	var start = new Date().getTime();
	var lastScreenshotTime = 0;
	chromeWindow.activeTab.url = "http://" + url;

	// While loading, make screenshots.
	while (w.activeTab.loading()) {
		var end = new Date().getTime();
		var time = end - start;
		
		if (time > loadTimeout) {
			break;
		}
		
		if (time - lastScreenshotTime > screencapFreq) {
			while (lastScreenshotTime < time) {
				lastScreenshotTime += screencapFreq;
			}
			lastScreenshotTime -= screencapFreq;
			screencap(chromeWindow, terminal, url + "/" + lastScreenshotTime);
		}
		// console.log("loading...");
	}

	var end = new Date().getTime();
	var time = end - start;
	if (time > loadTimeout) {
		time = loadTimeout;
	}

	delay(0.1);
	
	screencap(chromeWindow, terminal, url);
	screencap(chromeWindow, terminal, url + "/" + time);
	
	console.log("Loading\t" + url + "\t" + time);
	doScript(terminal, 'echo "' + url + ',' + time + '" >> ' + csvPath);
	
}


var ch = Application('Google Chrome');
var w = ch.windows()[0];
var term = Application("Terminal");

var urls = [

"google.gr",
"zougla.gr",
"fanpage.gr",
"protothema.gr",
"newsit.gr",
"makeleio.gr",
"iefimerida.gr",
"in.gr",
"tro-ma-ktiko.blogspot.gr",
"newsbomb.gr",
"news247.gr",
"skroutz.gr",
"gazzetta.gr",
"defencenet.gr",
"kathimerini.gr",
"diaforetiko.gr",
"enikos.gr",
"skai.gr",
"lifo.gr",
"naftemporiki.gr",
"sport24.gr",
"capital.gr",
"newsbeast.gr",
"alfavita.gr",
"newpost.gr",
"koutipandoras.gr",
"huffingtonpost.gr",
"altsantiri.gr",
"sport-fm.gr",
"tovima.gr",
"winbank.gr",
"alpha.gr",
"thetoc.gr",
"newsone.gr",
"real.gr",
"ethnos.gr",
"tvxs.gr",
"parapolitika.gr",
"car.gr",
"ert.gr",
"meteo.gr",
"imerisia.gr",
"eurobank.gr",
"contra.gr",
"nbg.gr",
"gsis.gr",
"taxheaven.gr",
"athensvoice.gr",
"topontiki.gr",
"olympia.gr",
"sportdog.gr",
"tanea.gr",
"vrisko.gr",
"tlife.gr",
"sdna.gr",
"zappit.gr",
"insomnia.gr",
"gossip-tv.gr",
"toxwni.gr",
"efsyn.gr",
"dikaiologitika.gr",
"newmoney.gr",
"live24.gr",
"e-shop.gr",
"xe.gr",
"piraeusbank.gr",
"ypes.gr",
"athensmagazine.gr",
"antenna.gr",
"star.gr",
"euro2day.gr",
"protagon.gr",
"plaisio.gr",
"xo.gr",
"pentapostagma.gr",
"ingossip.gr",
"alphatv.gr",
"onsports.gr",
"patrasevents.gr",
"stoiximan.gr",
"thepressproject.gr",
"mixanitouxronou.gr",
"left.gr",
"e-radio.gr",
"crashonline.gr",
"ipaideia.gr",
"news.gr",
"filathlos.gr",
"oneman.gr",
"public.gr",
"opap.gr",
"bestprice.gr",
"arouraios.gr",
"sch.gr",
"kontranews.gr",
"avgi.gr",
"agioritikovima.gr",
"bankingnews.gr",
"newsrebel.gr",
"redder.gr",
"uoa.gr",
"athinorama.gr",
"bet365.gr",
"newsauto.gr",
"nooz.gr",
"viva.gr",
"amna.gr",
"madata.gr",
"oaed.gr",
"pinnokio.gr",
"freepen.gr",
"papaki.gr",
"fimotro.blogspot.gr",
"skywalker.gr",
"diavgeia.gov.gr",
"wind.gr",
"auth.gr",
"flashnews.gr",
"iskra.gr",
"cretalive.gr",
"info-war.gr",
"freemeteo.gr",
"stokokkino.gr",
"tripadvisor.com.gr",
"ladylike.gr",
"fnews.gr",
"tribune.gr",
"myphone.gr",
"mikroskopio.gr",
"forthnet.gr",
"queen.gr",
"nonews-news.blogspot.gr",
"pathfinder.gr",
"mediamarkt.gr",
"aftodioikisi.gr",
"sentragoal.gr",
"katohika.gr",
"kotsovolos.gr",
"e-food.gr",
"lidl-hellas.gr",
"onmed.gr",
"sintagespareas.gr",
"any-news.gr",
"cosmote.gr",
"thestival.gr",
"oikiaka.gr",
"govastileto.gr",
"palo.gr",
"blog-spot.gr",
"boro.gr",
"thebest.gr",
"press-news.gr",
"e-daily.gr",
"candianews.gr",
"astrology.gr",
"onalert.gr",
"hysteria.gr",
"dimokratiki.gr",
"ntua.gr",
"usay.gr",
"sofokleousin.gr",
"david-avramidis.gr",
"kariera.gr",
"redplanet.gr",
"topnews.gr",
"spitogatos.gr",
"entertv.gr",
"antinews.gr",
"vodafone.gr",
"cam4.gr",
"koolnews.gr",
"newsnea.gr",
"ote.gr",
"lykavitos.gr",
"frontpages.gr",
"lamiareport.gr",
"matrix24.gr",
"allyou.gr",
"avopolis.gr",
"games.gr",
"prisonplanet.gr",
"sportit.gr",
"pblogs.gr",
"epixeiro.gr",
"masternews.gr",
"fpress.gr",
"enallaktikos.gr",
"tilegrafima.gr",
"praktiker.gr",
"seleo.gr",
"gavros.gr",
"trelokouneli.gr",
"techgear.gr",
"prasinanea.gr",
"cretapost.gr",
"fimes.gr",
"otenet.gr",
"otherside.gr",
"athenstimeout.gr",
"leoforos.gr",
"iatropedia.gr",
"toratora.gr",
"11888.gr",
"neolaia.gr",
"fthis.gr",
"tff.gr",
"hellenicparliament.gr",
"okairos.gr",
"ikea.gr",
"minedu.gov.gr",
"popaganda.gr",
"escore.gr",
"manslife.gr",
"triklopodia.gr",
"stoxos.gr",
"all4woman.gr",
"olagossip.gr",
"yupiii.gr",
"ika.gr",
"syllogi.gr",
"902.gr",
"newsitamea.gr",
"groupon.gr",
"infokids.gr",
"techblog.gr",
"biblionet.gr",
"sansimera.gr",
"clickatlife.gr",
"axortagos.gr",
"voicenews.gr",
"agones.gr",
"autoblog.gr",
"scoops.gr",
"epirusgate.blogspot.gr",
"lexigram.gr",
"airtickets.gr",
"sportingbet.gr",
"realbomb.gr",
"elta.gr",
"oroskopos.gr",
"ipop.gr",
"myastro.gr",
"pcsteps.gr",
"vita.gr",
"hol.gr",
"paraskhnio.gr",
"ienimerosi.gr",
"followme.gr",
"voria.gr",
"upatras.gr",
"archangelosmichail.gr",
"newsonly.gr",
"in2life.gr",
"trikalanews.gr",
"dinfo.gr",
"koyzoylo.gr",
"novasports.gr",
"periodista.gr",
"spartoo.gr",
"eap.gr",
"faysbook.gr",
"taxydromiki.gr",
"zoo.gr",
"tophost.gr",
"trivago.gr",
"multi-news.gr",
"dei.gr",
"agriniopress.gr",
"anemosantistasis.blogspot.gr",
"larissanet.gr",
"womenonly.gr",
"4ty.gr",
"iatronet.gr",
"airbnb.gr",
"duth.gr",
"astynomia.gr",
"aggeliopolis.gr",
"tospitimou.gr",
"digitallife.gr",
"mama365.gr",
"mothersblog.gr",
"singleparent.gr",
"weather.gr",
"espressonews.gr",
"proson.gr",
"jenny.gr",
"paradrasi.gr",
"apodytiriakias.gr",
"mazemata.gr",
"mfa.gr",
"newsking.gr",
"1001paixnidia.gr",
"linelife.gr",
"alertgr.blogspot.gr",
"fouit.gr",
"carrefour.gr",
"forth-crs.gr",
"autotriti.gr",
"myshoe.gr",
"rua.gr",
"tee.gr",
"sintagoulis.gr",
"et.gr",
"olapaok.gr",
"gameworld.gr",
"brandsgalaxy.gr",
"kozan.gr",
"tsantiri.gr",
"freestuff.gr",
"aegean.gr",
"betarades.gr",
"uth.gr",
"wedia.gr",
"ellinofreneianet.gr",
"rodiaki.gr",
"malihu.gr",
"greek-language.gr",
"newsclub.gr",
"sugklonistiko.gr",
"zarpanews.gr",
"on-news.gr",
"piraeuspress.gr",
"pamepreveza.gr",
"imommy.gr",
"amfipolinews.blogspot.gr",
"takaluteraedo.blogspot.gr",
"politeianet.gr",
"lamiastar.gr",
"grserver.gr",
"enikonomia.gr",
"argiro.gr",
"you.gr",
"reporter.gr",
"creteplus.gr",
"thesecretrealtruth.blogspot.gr",
"makedonias.gr",
"grekamag.gr",
"defence-point.gr",
"iphonehellas.gr",
"cyclades24.gr",
"joytv.gr",
"olivemagazine.gr",
"rizospastis.gr",
"kalimera-arkadia.gr",
"wibis.gr",
"dexiextrem.blogspot.gr",
"perierga.gr",
"bankofgreece.gr",
"anonymoigr.blogspot.gr",
"xstream.gr",
"agriniotimes.gr",
"astrologos.gr",
"gameover.gr",
"nostimonimar.gr",
"agelioforos.gr",
"grnet.gr",
"zoornalistas.blogspot.gr",
"homemarkt.gr",
"ysterografa.gr",
"dreamfm.gr",
"agronews.gr",
"eleysis-ellinwn.gr",
"oasa.gr",
"piraeusview.gr",
"prosoccer.gr",
"logiastarata.gr",
"marieclaire.gr",
"agrinionews.gr",
"referendum2015gov.gr",
"typologies.gr",
"sarotiko.gr",
"skaikairos.gr",
"metrosport.gr",
"stigmap.gr",
"aueb.gr",
"spirospero.gr",
"neakriti.gr",
"eleftheriaonline.gr",
"express.gr",
"ishow.gr",
"platform.gr",
"analyst.gr",
"missbloom.gr",
"aixmi.gr",
"skroutzstore.gr",
"uoc.gr",
"visitgreece.gr",
"patratora.gr",
"asep.gr",
"erodate.gr",
"enimerosi24.gr",
"esos.gr",
"michanikos.gr",
"2winbet.gr",
"hcmr.gr",
"okokoras.gr",
"7imeres.gr",
"superbasket.gr",
"voliotaki.blogspot.gr",
"getgreekmusic.gr",
"newsmusic.gr",
"ebasket.gr",
"uom.gr",
"thelab.gr",
"alterthess.gr",
"freegossip.gr",
"flowmagazine.gr",
"villagecinemas.gr",
"whatsup.gr",
"minitek.gr",
"primeminister.gov.gr",
"koinignomi.gr",
"agrotypos.gr",
"forth.gr",
"nocomments.gr",
"ogdoo.gr",
"karfitsa.gr",
"fumara.gr",
"flix.gr",
"gtp.gr",
"goldenbrands.gr",
"phorum.gr",
"corfuland.gr",
"harryklynn.blogspot.gr",
"larisanew.gr",
"hellenicseaways.gr",
"spiti24.gr",
"kerdos.gr",
"teicrete.gr",
"tornosnews.gr",
"e-jumbo.gr",
"taxalia.blogspot.gr",
"akous.gr",
"e-prescription.gr",
"allaksogolies.gr",
"protoporia.gr",
"tradenow.gr",
"unipi.gr",
"gnomikologikon.gr",
"griechenland-blog.gr",
"infognomonpolitics.blogspot.gr",
"teiath.gr",
"protoselidaefimeridon.gr",
"ab.gr",
"ekdromi.gr",
"saveandwin.gr",
"neolagoniko.blogspot.gr",
"romfea.gr",
"enet.gr",
"hitandrun.gr",
"kinima-ypervasi.blogspot.gr",
"eklogika.gr",
"anatropionline.gr",
"diadoseto.blogspot.gr",
"cosmodata.gr",
"ereportaz.gr",
"cosmossport.gr",
"pressaris.gr",
"ired.gr",
"nafpaktianews.gr",
"diorismos.gr",
"noiz.gr",
"kamikaze.gr",
"clickdelivery.gr",
"pamesports.gr",
"greek-sites.gr",
"parents.org.gr",
"newsbit.gr",
"adman.gr",
"pelop.gr",
"egnomi.gr",
"e-dimosio.gr",
"metar.gr",
"idreamteam.gr",
"forologikanea.gr",
"pamediakopes.gr",
"traveldailynews.gr",
"deliveras.gr",
"hcg.gr",
"i-pet.gr",
"england365.gr",
"culturenow.gr",
"runningnews.gr",
"onlarissa.gr",
"pestaola.gr",
"gocar.gr",
"instyle.gr",
"uoi.gr",
"daddy-cool.gr",
"typosthes.gr",
"whocallsme.gr",
"cyta.gr",
"e-mesara.gr",
"rocking.gr",
"avclub.gr",
"galinos.gr",
"dete.gr",
"tostoixima.gr",
"hiphop.gr",
"paokmania.gr"


];



for (i in urls) {
	getUrl(w, term, urls[i]);
}
                              &¶jscr  úÞÞ­